//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertEmail
    {
        public int AlertEmail_ID { get; set; }
        public string AlertEmail_content { get; set; }
        public string Staff_ID { get; set; }
        public System.DateTime SendDate { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
