//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferencePerson
    {
        public int ReferencePersonID { get; set; }
        public string FullName { get; set; }
        public string Position { get; set; }
        public string Company { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public int ProfileID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
